version: '3'

services:

  client:
    container_name: react-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3005
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true